const STORE_CONST = {
  SET_USER: "SET_USER",
  ADD_NEW_ITEM_TO_BASKET: "ADD_NEW_ITEM_TO_BASKET",
  ADD_ITEM_FROM_BASKET: "ADD_ITEM_FROM_BASKET",
  REMOVE_ITEM_FROM_BASKET: "REMOVE_ITEM_FROM_BASKET",
  REMOVE_ALL_ITEMS_FROM_BASKET: "REMOVE_ALL_ITEMS_FROM_BASKET",
  EMPTY_BASKET: "EMPTY_BASKET"
}

export default STORE_CONST